name: AirChainPay CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airchainpay-contracts
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './airchainpay-contracts/package-lock.json'
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat test

  test-relay:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airchainpay-relay
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './airchainpay-relay/package-lock.json'
      - run: npm ci
      - run: npm run lint
      - run: npm test

  build-wallet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airchainpay-wallet
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './airchainpay-wallet/package-lock.json'
      - run: npm ci
      - run: npx expo install --check
      - name: Check TypeScript
        run: npx tsc --noEmit

  deploy-relay:
    needs: [test-contracts, test-relay]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./airchainpay-relay
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./airchainpay-relay
          push: true
          tags: airchainpay/relay:latest,airchainpay/relay:${{ github.sha }}
      
      # Add deployment steps here (e.g., to AWS, Azure, GCP, etc.)
      # This is just a placeholder for actual deployment steps 